### ISSUE TITLE
install sdc7 grub error 21 

### ISSUE THREAD

**Issue by hqs88** [joyent/sdc#160]
why usb key can't install

**Comment by lloydde** [comment]
What instructions are you following? What step in the instructions are you at?

This isn't an area I'm familiar with, but looking at boot/grub/grub.conf on a USB key, I don't see any drive specific logic. Is it locally attached [SAS/SATA](https://docs.joyent.com/sdc7/sdc7-minimium-requirements#disk)? Is the BIOS detecting it?

Grub error:
~~~
21 : Selected disk does not exist
      This error is returned if the device part of a device- or full
      file name refers to a disk or BIOS device that is not present or
      not recognized by the BIOS in the system.
~~~

**Comment by hqs88** [comment]
thank you very much
