### ISSUE TITLE
SDC7 Virtual Machines Tab -> Virtual Machine Unable to fetch User Information

### ISSUE THREAD

**Issue by ceizner** [joyent/sdc#161]
in SDC7 when selecting any VM on the right side of the screen under user icon there is always a message: Unable to fetch User Information.<UUID>

**Comment by bahamat** [comment]
Filed internally as ADMIN-2066. This issue should be opened against sdc-adminui.

**Comment by ceizner** [comment]
Here is the example: http://ryan.net/misc/skitch/montgomery___Operations_Portal_1AFBE22B.png

**Comment by ceizner** [comment]
![error](https://cloud.githubusercontent.com/assets/12173436/7522784/57ce6952-f4ac-11e4-812e-93870256ba46.jpg)

**Comment by pannon** [comment]
We are experiencing the same issue on both of our SDC setups. The last one was upgraded from version `20150305` to `release-20150430`.

**Comment by bahamat** [comment]
The commit that caused this is joyent/sdc-adminui@001f6ea.

**Comment by bahamat** [comment]
This has been fixed in adminui@release-20150514-20150518T174827Z-gde7e8f1 and is now available from the release channel.
