### ISSUE TITLE
CoaL problems on Ubuntu 14.04

### ISSUE THREAD

**Issue by jgrowl** [joyent/sdc#167]
Not sure if I missed a step or if there is a problem with my vmware install but I am not able to get things working using Ubuntu 14.04 and VMware 11.1.2.

When I run the setup script this is what I get:
```
% curl -s https://raw.githubusercontent.com/joyent/sdc/master/tools/coal-linux-vmware-setup | sudo bash
Admin network:    network="10.99.99.0", mac ip="10.99.99.254", netmask="255.255.255.0"
External network: network="10.88.88.0", mac ip="10.88.88.1", netmask="255.255.255.0"
Setup VMWare networking: admin network 10.99.99.0, external network 10.88.88.0
Changing VMware locations settings...
Old locations settings backed up to the following files:
/etc/vmware/locations.pre_coal
Changing VMware networking settings...
Old networking settings backed up to the following files:
/etc/vmware/networking.pre_coal
Changing vmnet interface permissions...
Restarting VMware services...
Stopped Bridged networking on vmnet0
Stopped DHCP service on vmnet1
Disabled hostonly virtual adapter on vmnet1
Stopped DHCP service on vmnet8
Stopped NAT service on vmnet8
Disabled hostonly virtual adapter on vmnet8
Stopped all configured services on all networks
Started Bridge networking on vmnet0
Subnet on vmnet1 is no longer available for usage, please run the network editor to reconfigure different subnet
Started NAT service on vmnet8
Enabled hostonly virtual adapter on vmnet8
Started DHCP service on vmnet8
Failed to start some/all services
```

When I try to boot up the headnode by selecting 'Live 64-bit' I get a black screen that does not ever seem to progress from there. Pressing 'c' doesn't have an effect.

**Comment by rmustacc** [comment]
@jgrowl By default, it's going to boot to the serial console. So you'll want to follow the instructions in grub that are documented in the README here: https://github.com/joyent/sdc. See the portion that starts with:

```
6. Boot the headnode.
```

**Comment by jgrowl** [comment]
@rmustacc Derp! I thought it was saying to hit enter on "Live 64-bit" before pressing 'c'. That seems to get me to the next step. I should have realized since it was grub config. Thanks!

**Comment by rmustacc** [comment]
No worries, if we can better clarify the documentation there, please let us know.

**Comment by lloydde** [comment]
@jgrowl you are not a first to encounter this issue. grub ux is a pretty foreign. What do you think of the instructions at https://github.com/joyent/sdc/blob/master/docs/developer-guide/coal-setup.md#download-coal-and-configure-vmware step 6 and the image there?

**Comment by jgrowl** [comment]
@lloydde That looks great. Perhaps changing the wording from

> **Select** the "Live 64-bit" option and press 'c' to enter the command line for GRUB

to 

> **Highlight** the "Live 64-bit" option and press 'c' to enter the command line for GRUB

would make things even more clear. Regardless, looks good. :+1:

**Comment by lloydde** [comment]
@jgrowl good call, I was also thinking of changing "to enter" to "to go to". I'll make those changes now.
