### ISSUE TITLE
CoaL upgrade doc has 2 commands that do not work properly

### ISSUE THREAD

**Issue by numericillustration** [joyent/sdc#178]
1. the agent update command has changed from `sdcadm experimental update-agents --latest -y` to `sdcadm experimental update-agents --all --latest -y`

2. the command to gather the latest PI after installing the latest doesn't account for multiple lines having the word `true` in it resulting in multiple PIs being assigned to `LATEST_PLATFORM` which causes the `sdcadm platform assign $LATEST_PLATFORM --all` command to fail.  I'm told this is due to the fact that `the “default” column is new as of 20150820.`

fixes for both are included in:
https://github.com/joyent/sdc/pull/177

**Comment by lloydde** [comment]
2. merged as joyent/sdc@b08729b.

**Comment by lloydde** [comment]
Thanks @numericillustration!
