### ISSUE TITLE
Cannot run post-setup common-external-nics

### ISSUE THREAD

**Issue by matthiasg** [joyent/sdc#189]
I am trying to follow https://github.com/joyent/sdc/blob/master/docs/developer-guide/coal-setup.md but am experiencing some issues which prevent me from running `sdcadm experimental update-docker --servers cns,headnode` and `sdcadm post-setup cloudapi`. They might be related to some failed jobs as listed in the web interface, if so what should i do ? can i rerun those jobs ?

<img width="858" alt="screen shot 2016-01-21 at 22 48 10" src="https://cloud.githubusercontent.com/assets/231889/12495629/14c8b430-c091-11e5-9d81-1390178f5ccd.png">

1) running `sdcadm post-setup common-external-nics` fails with:

`sdcadm post-setup: error: {"id":"379cb210-a459-498e-ae94-dffaa3e11be4","task":"machine_update","server_uuid":"564df79a-15b3-4722-4e98-01c6a523ed85","status":"failure","timestamp":"2016-01-21T21:31:50.231Z","history":[{"name":"error","timestamp":"2016-01-21T21:31:50.585Z","event":{"error":{"message":"requests must originate from CNAPI address"}}},{"name":"finish","timestamp":"2016-01-21T21:31:50.585Z","event":{}}],"req_id":"e5d1f84c-4cdb-e9e6-ef75-bc4152ee86e8"}`

This error was already mentioned in December by someone else on irc but nobody seems to have answered (see http://echelog.com/logs/browse/smartos/1450306800) 

2) In general the setup didnt match up exactly with the blog post, most likely because the services and tools have changed since the article was published. The only thing i would like to know whether the healthcheck should look like the list below now, since it seems to miss a few services compared to the original post.

[root@headnode (coal-1) ~]# sdc-healthcheck
ZONE                                 STATE           AGENT               STATUS
global                               running         -                   online
assets                               running         -                   online
sapi                                 running         -                   online
binder                               running         -                   online
manatee                              running         -                   online
moray                                running         -                   online
amonredis                            running         -                   online
redis                                running         -                   online
ufds                                 running         -                   online
workflow                             running         -                   online
amon                                 running         -                   online
sdc                                  running         -                   online
papi                                 running         -                   online
napi                                 running         -                   online
rabbitmq                             running         -                   online
imgapi                               running         -                   online
cnapi                                running         -                   online
dhcpd                                running         -                   online
fwapi                                running         -                   online
vmapi                                running         -                   online
ca                                   running         -                   online
mahi                                 running         -                   online
adminui                              running         -                   online
global                               running         ur                  online
global                               running         smartlogin          online

Env: MBPr,VMWare Fusion Pro.

**Comment by matthiasg** [comment]
I just reran the entire process and it works now. during the setup process there also wasnt any issue checking connectivity to the default dns servers.

so just retry/rerun did it for me

**Comment by J-C-B** [comment]
Hi,

I had the same error when trying to provision or make any changes via sdc ui or cli - so i ran these commands and then i can provision and do whatever... until the next reboot and a have to do it again

https://github.com/J-C-B/smartos-notes/blob/master/CNAPI-error-fix.sh

hope this helps in future
