### ISSUE TITLE
old crusty hardware won't boot from a SmartOS USB key. will boot a DVD...

### ISSUE THREAD

**Issue by andrewrothstein** [joyent/sdc#200]
In my eBay garbology experiments I've picked up a supermicro x7-dbr-e running the latest bios and firmware. I'm trying to boot it as an SDC compute node. challenge is that it won't boot from any of the USB slots. it claims to but I've tried and tried again. it does have a slim dvd drive. I got it to iPXE boot from the DVD drive and boot up as a compute node. yay! challenge is it won't "register" without adjusting its network configuration. I think it's choking on that step because there's no usb key to write the updated config to. does any of this make any sense? do you think it will work if I put the USB key in even if it's not the boot device? anyone have a strategy for hacking around an old crusty system that won't boot from a USB key?

thanks, Andrew

**Comment by rmustacc** [comment]
On 5/8/16 20:16 , Andrew Rothstein wrote:
> In my eBay garbology experiments I've picked up a supermicro x7-dbr-e running the latest bios and firmware. I'm trying to boot it as an SDC compute node. challenge is that it won't boot from any of the USB slots. it claims to but I've tried and tried again. it does have a slim dvd drive. I got it to iPXE boot from the DVD drive and boot up as a compute node. yay! challenge is it won't "register" without adjusting its network configuration. I think it's choking on that step because there's no usb key to write the updated config to. does any of this make any sense? do you think it will work if I put the USB key in even if it's not the boot device? anyone have a strategy for hacking around an old crusty system that won't boot from a USB key?

Hmm, it's a bit odd that all the USB fails. Is that something that's
failing in the supermicro firmware?

In general, if the USB key can't work, you should be able to use
traditional PXE booting and shouldn't need to rely on the DVD drive.

As for the setup failure, @jclulow, does that sound familiar to you?

**Comment by andrewrothstein** [comment]
to be clear, I got the node to iPXE boot. the challenge I'm having is that it won't register. I'm going to open a separate issue for that. thanks for the tips!
