### ISSUE TITLE
compute node won't register

### ISSUE THREAD

**Issue by andrewrothstein** [joyent/sdc#201]
got my first compute node to iPXE boot - yay! unfortunately having problems getting it to register. it's failing on the cnapi.execute_agentsetup_script step. if I'm reading the job details correctly it looks like

```
      "result": "",
      "error": {
        "message": "Error executing on remote system",
        "statusCode": 500,
        "body": {
          "code": "InternalError",
          "message": "Error executing on remote system"
        },
        "restCode": "InternalError",
        "name": "InternalError"
      },
      "name": "cnapi.execute_agentsetup_script",
      "started_at": "2016-05-13T03:44:10.655Z",
      "finished_at": "2016-05-13T03:44:15.223Z"
    }
```

I'm a total noob so no suggestion is too obvious here. I get that it's trying to setup the compute agent on the compute node. Do you think it's connectivity issue between the headnote and the compute node? I'm able to ssh as root between them on the admin network. is the cnapi running on the headnote not accessible to the compute node? is there some magical svcs command to help me diagnose?

Thanks for any tips!

-Andrew

**Comment by jclulow** [comment]
Hi Andrew,

The workflow job that is executing here is defined in [lib/workflows/server-setup.js](https://github.com/joyent/sdc-cnapi/blob/master/lib/workflows/server-setup.js) in the CNAPI repository.  The specific step in the chain that appears to be failing for you is [cnapi.execute_agentsetup_script](https://github.com/joyent/sdc-cnapi/blob/master/lib/workflows/server-setup.js#L422-L427).  If we look at the implementation of that step, i.e. [executeAgentSetupScript](https://github.com/joyent/sdc-cnapi/blob/master/lib/workflows/server-setup.js#L144-L173), we see that it runs the following on the compute node:

```javascript
    var script = [
        '#!/bin/bash',
        'set -o xtrace',
        'cd /var/tmp',
        'echo ASSETS_URL = $ASSETS_URL',
        './agentsetup.sh'
    ].join('\n');
```

The script in question is [agentsetup.sh](https://github.com/joyent/sdc-headnode/blob/master/scripts/agentsetup.sh) from the `sdc-headnode` repository.  This was downloaded from the copy on your headnode via the `assets` zone in an earlier step of the server setup workflow job.  If we look in this script, we can see that it logs to a specific file on the compute node where setup is running:

```
...
exec > >(tee /var/log/agent-setup.log)
...
```

What is in this file (`/var/log/agent-setup.log`) on the compute node in question?

It may also help to look at the CNAPI log to see if there is more detail about the `InternalError`.  In the `cnapi0` zone on the headnode, you'll want to look at either the current CNAPI log with `bunyan $(svcs -L cnapi)`; or potentially (if this occurred more than an hour ago) in a previously rotated file in `/var/log/sdc/upload`.  The rotated file name will include the date stamp, so you should be able to zero in on the particular time your request failed.

**Comment by andrewrothstein** [comment]
Thanks for the tips! My heavy handed solution was to upgrade the headnode, reboot the headnode, followed by a reboot on my compute node. After all of that recycling it registered. I'm going to do the archaeological dig to figure out wtf happened.
