### ISSUE TITLE
Why the software history was not kept?

### ISSUE THREAD

**Issue by gustavopinto** [joyent/sdc#202]
Hi there, 

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. **sdc** was in my list. However, I observed that the software history of when the software was developed as a proprietary software was not kept after the transition to Github.

Knowing that software history is indispensable for developers (e.g., developers need to refer to history several times a day), I would like to ask **sdc** developers the following four brief questions:

1. Why did you decide to not keep the software history?
2. Do the _core developers_ faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
3. Do the _newcomers_ faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
4. How does the lack of history impacted on software evolution? Does it placed any burden in understanding and evolving the software?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by rmustacc** [comment]
On 5/18/16 8:39 , Gustavo wrote:
> Hi there, 
> 
> I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. **sdc** was in my list. However, I observed that the software history of when the software was developed as a proprietary software was not kept after the transition to Github.

Which repositories are you referring to? Almost everything to my
knowledge has its source intact.

**Comment by davepacheco** [comment]
We very much agree that the software history is extremely useful for developers, and I believe we preserved it for nearly all of the repositories that were open-sourced as part of the SDC and Manta projects.

**Comment by gustavopinto** [comment]
Hi @davepacheco, thank you for you time. Your explanation in the other issue was valuable, so I'm closing this one too.

Thanks once again.

Gustavo

**Comment by gustavopinto** [comment]
Hi @davepacheco, 

thanks once again for answering our research inquiries. We were able to collect 35 responses and we drafted a research paper with the results. The paper was submitted and accepted for the 14th International Conference on Open Source Systems (http://oss2018.org/). You can find the paper [here](http://gustavopinto.org/lost+found/oss2018.pdf). Hope you enjoy reading the paper!

Thanks again,

Gustavo

**Comment by davepacheco** [comment]
Thanks for the pointer!
