### ISSUE TITLE
Upgrading SDC platform image

### ISSUE THREAD

**Issue by pannon** [joyent/sdc#40]
The documentation [here](https://docs.joyent.com/sdc7/installing-a-new-sdc-platform-image#DownloadtheImage) suggests to download a new platform image via a customized example link.

Unless I missed something in the docs - where are these platform images located for download?

**Comment by bahamat** [comment]
Can you open this against [joyent/documentation](/joyent/documentation/issues) instead?

**Comment by trentm** [comment]
@pannon Most of the docs on docs.joyent.com were written for the Joyent Public Cloud (JPC) and for Joyent customers of SmartDataCenter... before SDC was open sourced. That means that while there is a lot of documentation there that is helpful for SDC usage, there are a lot of cases where they describe things that aren't correct for open source SDC usage.

You hit one difference here: the platform image. Joyent customers of SmartDataCenter (i.e. those with a support contract), are given specific platform builds that are QA'd/tested by the support group. They are a subset of all the platform builds.  For open source SDC usage all the platforms are available at /Joyent_Dev/public/builds/platform in Manta. For example, a build for the latest bi-weekly release branch is here:

https://us-east.manta.joyent.com/Joyent_Dev/public/builds/platform/release-20150108-20150108T081734Z/platform/platform-release-20150108-20150108T081734Z.tgz

I'll open a ticket on the repo that holds the docs.joyent.com docs to update the notes on that page. Thanks.

**Comment by pannon** [comment]
Great thanks!
