### ISSUE TITLE
Cannot create custom image

### ISSUE THREAD

**Issue by sigxcpu76** [joyent/sdc#44]
I'm trying to create a custom image using Ubuntu 14.04 cloud edition from here: https://cloud-images.ubuntu.com/trusty/current/trusty-server-cloudimg-amd64-disk1.img.

What I do (on headnode):
- qemu-img convert -O raw trusty.img trusty.raw
- zfs create -V 16g zones/ubuntu/disk
- dd if=trusty.img of=/dev/zvol/rdsk/zones/ubuntu.disk bs=1024k
- zfs snapshot zones/ubuntu/disk@send
- zfs send zones/ubuntu/disk@send | gzip > ubuntu.zfs.gz
- use this manifest
```javascript
{
  "v": 2,
  "uuid": "86bb31ca-a888-11e4-b6d2-c79183d409bf",
  "owner": "4a361963-67c1-4f04-daf2-e2d3cf54bb78",
  "name": "ubuntu-14.04",
  "version": "1.0.0",
  "state": "active",
  "disabled": false,
  "public": true,
  "type": "zvol",
  "os": "linux",
  "description": "Ubuntu 14.04 64-bit image with just essential packages installed. Ideal for users who are comfortable with setting up their own environment and tools.",
  "urn": "sdc:tcn:ubuntu-14.04:1.0.0",
  "requirements": {
    "networks": [
      {
        "name": "net0",
        "description": "public"
      }
    ],
    "ssh_key": true
  },
  "nic_driver": "virtio",
  "disk_driver": "virtio",
  "cpu_type": "qemu64",
  "image_size": 16384
}
```
- sdc-imgadm import -m ubuntu.manifest -f ubuntu.zfs.gz

Everything looks fine up to this point, the image is imported, shown by both Operations Portal and CloudAPI.

Creating a VM out of it stays in "provisioning" for ages until it times out. On the other hand, the "provisioner" logs on the headnode (used as compute node) show:

```javascript
{"name":"/opt/smartdc/agents/lib/node_modules/provisioner/lib/tasks/machine_create","req_id":"f6ded340-a891-11e4-8ec8-a3d6bdbf6ad1","hostname":"headnode","pid":54623,"level":30,"action":"create","vm":"d3d96226-1aae-49e0-8069-de35708d6a07","time":"2015-01-30T15:09:23.620Z","component":"machine_create","msg":"defaulting to refreservation = 16384","v":0}
{"name":"/opt/smartdc/agents/lib/node_modules/provisioner/lib/tasks/machine_create","req_id":"f6ded340-a891-11e4-8ec8-a3d6bdbf6ad1","hostname":"headnode","pid":54623,"level":30,"action":"create","vm":"d3d96226-1aae-49e0-8069-de35708d6a07","time":"2015-01-30T15:09:23.620Z","component":"machine_create","msg":"/usr/sbin/zfs get -Ho value name zones/86bb31ca-a888-11e4-b6d2-c79183d409bf@final","v":0}
{"name":"/opt/smartdc/agents/lib/node_modules/provisioner/lib/tasks/machine_create","req_id":"f6ded340-a891-11e4-8ec8-a3d6bdbf6ad1","hostname":"headnode","pid":54623,"level":30,"action":"create","vm":"d3d96226-1aae-49e0-8069-de35708d6a07","time":"2015-01-30T15:09:23.673Z","component":"machine_create","msg":"/usr/sbin/zfs clone -F -o refreservation=16384M zones/86bb31ca-a888-11e4-b6d2-c79183d409bf@final zones/d3d96226-1aae-49e0-8069-de35708d6a07-disk0","v":0}
{"name":"/opt/smartdc/agents/lib/node_modules/provisioner/lib/tasks/machine_create","req_id":"f6ded340-a891-11e4-8ec8-a3d6bdbf6ad1","hostname":"headnode","pid":54623,"level":50,"action":"create","vm":"d3d96226-1aae-49e0-8069-de35708d6a07","err":{"message":"Command failed: cannot create 'zones/d3d96226-1aae-49e0-8069-de35708d6a07-disk0': 'refreservation' is greater than current volume size\n","name":"Error","stack":"Error: Command failed: cannot create 'zones/d3d96226-1aae-49e0-8069-de35708d6a07-disk0': 'refreservation' is greater than current volume size\n\n at ChildProcess.exithandler (child_process.js:637:15)\n at ChildProcess.EventEmitter.emit (events.js:98:17)\n at maybeClose (child_process.js:743:16)\n at Process.ChildProcess._handle.onexit (child_process.js:810:5)","code":1,"signal":null},"volume":{"image_uuid":"86bb31ca-a888-11e4-b6d2-c79183d409bf" 
```
Full error log is here: https://gist.github.com/sigxcpu76/90b6042fbc4cc2752745

The *volsize* of the imported volume is 2.2GB (the size of the ubuntu cloud QEMU image) instead of 16GB as set in the original zfs create.

Another option was to use the image_size and volsize of 2252m which is the size of the raw file.

Now the error is thrown by https://github.com/joyent/smartos-live/blob/master/src/vm/node_modules/VM.js at line 607 saying that 2252 is incorrect, it should be 16384 (where it gets this value is beyond my understanding).

**Comment by chorrell** [comment]
Those images, afaik, have not been tested under or validated against SDC/SmartOS.

I really do not know if they will work under SDC.

Also, typically for the KVM linux images, we use and image_size of 10240

**Comment by sigxcpu76** [comment]
Thanks for your answer, but ignoring linux, having a raw disk image (from OVF or another virtualization platform, a backup or whatever source) what is the right way to create the image in SDC?
If image_size is the exact size, it complains that it is not 16384 (where does that value come, afterall? The VM.js source code shows that it is data.manifest.image_size, but that is not 16384, checked and -rechecked).
If it is 16384, it complains about refreservation being wrong.

**Comment by chorrell** [comment]
Hi,

For building an image from scratch for SDC, this is what you would typically do:

https://docs.joyent.com/sdc7/working-with-images/how-to-create-a-kvm-image

The above instructions mention  "Obtain VMTools ISO from Joyent correspoding to your OS" with a link.

Ignore that :)

The downloadable ISO is out of date, so better to go to the source here:

https://github.com/joyent/sdc-vmtools

Clone that, then make the ISO yourself:

```
make all
```

We're be working to get an updated ISO made available and the doc updated.

For the actual image building process, my team does things a little differently to speed up the build process. We create a custom ISO with the appropriate guest tools installed and use that. Here's how we roll a custom Debian 7 ISO for example:

https://github.com/joyent/mi-debian

Also as an aside, we will eventually be releasing Ubuntu Certified (Ubuntu Cloud) images publicly to https://images.joyent.com which will include Ubuntu 14.04 images. Right now those images are only available in the Joyent Public Cloud. We're working with Canonical (who build the images for us) to make that happen.

**Comment by sigxcpu76** [comment]
Thank you for the detailed explanation.

Aren't the tools for running inside the VM? The issue is that I cannot even create the VM caused by a combination of factors:
- ZFS loses volsize property when doing zfs send and sets it to whatever real usage/size is
- libzfs does not allow a refreservation property larger than the volsize
- VM.js insists in using refreservation and/or pulls values with unknown source (that suggested 16384 which is not the "image_size" property in the manifest has no link to anything related to this VM: image manifest or provisioning package)

That it my issue. After getting past this, I can move on with vmtools :)

**Comment by chorrell** [comment]
Right, so what I'm suggesting is: Don't use trusty-server-cloudimg-amd64-disk1.img :)

Use the Ubuntu server 14.04 ISO and follow the SDC7 docs I linked to:

http://releases.ubuntu.com/14.04.1/ubuntu-14.04.1-server-amd64.iso

https://docs.joyent.com/sdc7/working-with-images/how-to-create-a-kvm-image

The cloud image you are trying to use is built specifically for Amazon EC2. Even if you get past your current issues, it won't work.

**Comment by sigxcpu76** [comment]
That was always the backup option.

The reason I raised this here is because I consider that there is a bug in VM.js or something in upper layers. Although the manifest's ```image_size``` property is set to ```2252```, it complains that ```2252``` is wrong and should be ```16384```. The source code shows that ```16384``` value being pulled from ```data.manifest.image_size``` property which is ... ```2252``` (shown by initial manifest used at image's creation and by ```sdc-imgadm get``` on that imported image).

It looks like a default value set somewhere (I cannot find anything in the whole repository).

**Comment by chorrell** [comment]
It's possible, but the core issue here is: Using an AMI cloud image to build an image for SDC isn't supported.

As far as I know, no one has attempted this before and nothing has been added to SDC to support this.
